version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: ediaz
      MYSQL_PASSWORD: ediaz
      MYSQL_ROOT_PASSWORD: root