server:
  port: 8282

security:
  jwt:
    secret: 3caa8cac542d2f130481351d6cf702e937f961846b7bb581de851fefe2b88cfd
    expiration-miliseconds: 86400000

spring:
#  sql:
#    init:
#      mode: always
#  security:
#    user:
#      name: ediaz
#      password: ediaz
#      roles: ADMIN
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #format_sql: true
        #show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3308/employee_db?useSSL=false&allowPublicKeyRetrieval=true
    username: ediaz
    password: ediaz

logging:
  level:
    org.springframework.security: DEBUG